#!/bin/bash
#image result is a gif, so this won't work need to convert it to jpg or gif. 
result=`curl -s -L https://www.gocomics.com/random/calvinandhobbes |grep "og:image" | grep assets| egrep -o 'https?://[^ ]+' | sed 's/\"//'`
wget -q --no-check-certificate -O suspended "$result"
